FROM node:14-alpine as builder

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build --prod 

FROM nginx:1.21.6-alpine

COPY --from=builder /app/dist/frontend /var/www/html

COPY ./conf.d /etc/nginx/conf.d

EXPOSE 80 443




	
