version: "3.7"

services:
  backend:
    container_name: python
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -u backend/src/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  nginx:
    container_name: core_frontend
    restart: always
    image: jonasal/nginx-certbot:latest
    env_file:
      - .env.nginx
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  frontend:
    container_name: angular
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: >
      sh -c "npm run build --prod"
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src

volumes:
  nginx_secrets:
