version: "3.7"

services:
  backend:
    container_name: python
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -u backend/src/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  frontend:
    image: frontend
    container_name: frontend
    environment:
      CERTBOT_EMAIL: "satufps2021@gmail.com"
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - /home/ubuntu/projects/letsencrypt:/etc/letsencrypt
